site_name: PicPac Documentation
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/aaalgo/picpac
site_description: 'Documentation for PicPac, an image streamer for deep learning.'

dev_addr: '0.0.0.0:8600'

pages:
  - Home: index.md
  - Importing Data: import.md
  - Streaming: stream.md
  - Configuration: config.md
